<?php

namespace DoctrineMongoDBHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class PostDocumentsPostsHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['importance'])) {
            $value = $data['importance'];
            $return = (int) $value;
            $this->class->reflFields['importance']->setValue($document, $return);
            $hydratedData['importance'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['firstName'])) {
            $value = $data['firstName'];
            $return = (string) $value;
            $this->class->reflFields['firstName']->setValue($document, $return);
            $hydratedData['firstName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['lastName'])) {
            $value = $data['lastName'];
            $return = (string) $value;
            $this->class->reflFields['lastName']->setValue($document, $return);
            $hydratedData['lastName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['title'])) {
            $value = $data['title'];
            $return = (string) $value;
            $this->class->reflFields['title']->setValue($document, $return);
            $hydratedData['title'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description'])) {
            $value = $data['description'];
            $return = (string) $value;
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['phoneNumber'])) {
            $value = $data['phoneNumber'];
            $return = (string) $value;
            $this->class->reflFields['phoneNumber']->setValue($document, $return);
            $hydratedData['phoneNumber'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['age'])) {
            $value = $data['age'];
            $return = (int) $value;
            $this->class->reflFields['age']->setValue($document, $return);
            $hydratedData['age'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['homeTeam'])) {
            $value = $data['homeTeam'];
            $return = (string) $value;
            $this->class->reflFields['homeTeam']->setValue($document, $return);
            $hydratedData['homeTeam'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['awayTeam'])) {
            $value = $data['awayTeam'];
            $return = (string) $value;
            $this->class->reflFields['awayTeam']->setValue($document, $return);
            $hydratedData['awayTeam'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['user'])) {
            $value = $data['user'];
            $return = (string) $value;
            $this->class->reflFields['user']->setValue($document, $return);
            $hydratedData['user'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['information'])) {
            $value = $data['information'];
            $return = (string) $value;
            $this->class->reflFields['information']->setValue($document, $return);
            $hydratedData['information'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['actions'])) {
            $value = $data['actions'];
            $return = $value;
            $this->class->reflFields['actions']->setValue($document, $return);
            $hydratedData['actions'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['tags'])) {
            $value = $data['tags'];
            $return = $value;
            $this->class->reflFields['tags']->setValue($document, $return);
            $hydratedData['tags'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['thumbnail'])) {
            $value = $data['thumbnail'];
            $return = $value;
            $this->class->reflFields['thumbnail']->setValue($document, $return);
            $hydratedData['thumbnail'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['created_time'])) {
            $value = $data['created_time'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['created_time']->setValue($document, clone $return);
            $hydratedData['created_time'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['visible'])) {
            $value = $data['visible'];
            $return = (bool) $value;
            $this->class->reflFields['visible']->setValue($document, $return);
            $hydratedData['visible'] = $return;
        }
        return $hydratedData;
    }
}